### 查询所有
#POST {{content_host}}/content/course/list?pageNo=1&pageSize=2
POST {{gateway_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": null,
  "courseName": "java",
  "publishStatus": null
}

### 查询课程分类
GET  {{content_host}}/content//course-category/tree-nodes

### 课程新增
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201000",
  "price": 0,
  "originalPrice": 0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "测试课程103",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "",
  "grade": "204001",
  "description": "",
  "objectives": ""
}

### 课程查询byId
GET {{content_host}}/content/course/1
Content-Type: application/json


### 课程修改
PUT {{content_host}}/content/course
Content-Type: application/json

{
  "id": 130,
  "charge": "201001",
  "price": 256,
  "originalPrice": 2,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "测试课程104",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "",
  "grade": "204001",
  "description": "",
  "objectives": ""
}

### 课程计划查询
GET {{content_host}}/content/teachplan/126/tree-nodes
Content-Type: application/json


### 新增课程计划--章,当grade为1时parentid为0
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "courseId": 74,
  "parentid": 0,
  "grade": 1,
  "pname": "新章名称 [点击修改]"
}

### 新增课程计划--节
POST {{content_host}}/content/123
Content-Type: application/json


### 课程计划删除--章
DELETE {{content_host}}/content/teachplan/280
Content-Type: application/json


### 课程计划删除--节
DELETE {{content_host}}/content/teachplan/123
Content-Type: application/json


### 课程教师信息查询
GET {{content_host}}/content/courseTeacher/list/72
Content-Type: application/json

### 新增修改课程教师信息
POST {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "courseId": 72,
  "teacherName": "wangxu3",
  "position": "java高级讲师2",
  "introduction": "111111",
  "photograph": "http://r3zc5rung.hd-bkt.clouddn.com/2424e25d-b3ff-4ea2-92a5-249af918a42dGDSzBXIgWuwMCiZ4",
  "createDate": "2021-12-25 17:44:07"
}

### 修改课程教师信息
POST {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "id": 1,
  "courseId": 72,
  "teacherName": "wangxu3",
  "position": "java高级讲师2",
  "introduction": "111111",
  "photograph": "http://r3zc5rung.hd-bkt.clouddn.com/2424e25d-b3ff-4ea2-92a5-249af918a42dGDSzBXIgWuwMCiZ4",
  "createDate": "2021-12-25 17:44:07"
}

### 删除课程教师信息 后面分别对应{courseId}/{id}
DELETE {{content_host}}/content/courseTeacher/course/72/22

### 删除课程
DELETE {{content_host}}/content/course/180



### 课程查询byId token
GET {{content_host}}/content/course/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODAzMjMxMDksImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImZhYzY5NTJkLTZmNDgtNDg0Ni05YmRmLWQ0MmE1ZDAwMmYzYiIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.U9FX4cJBfEAVb4P9rzR_dQuy3jgqfG-jYavSfBsvW7Q

### 课程查询byId token 通过网关
GET {{gateway_host}}/content/course/1
Authorization: Bearer 1yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODAzMjMxMDksImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImZhYzY5NTJkLTZmNDgtNDg0Ni05YmRmLWQ0MmE1ZDAwMmYzYiIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.U9FX4cJBfEAVb4P9rzR_dQuy3jgqfG-jYavSfBsvW7Q

### 课程查询byId token 通过网关 用户信息增强后
GET {{gateway_host}}/content/course/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJiaXJ0aGRheVwiOlwiMjAyMi0wOS0yOFQxOToyODo0NlwiLFwiY3JlYXRlVGltZVwiOlwiMjAyMi0wOS0yOFQwODozMjowM1wiLFwiaWRcIjpcIjUwXCIsXCJuYW1lXCI6XCLlrabnlJ8xXCIsXCJuaWNrbmFtZVwiOlwi5aSn5rC054mbXCIsXCJzZXhcIjpcIjFcIixcInN0YXR1c1wiOlwiMVwiLFwidXNlcm5hbWVcIjpcInN0dTFcIixcInVzZXJwaWNcIjpcImh0dHA6Ly9maWxlLjUxeHVlY2hlbmcuY24vZGRkZlwiLFwidXR5cGVcIjpcIjEwMTAwMVwifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODAzMzE0NzYsImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiMDBkNTgwMzEtMDk5MS00NjViLWI3YzgtNmMzNjliNWZhNTIyIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.Zr_cUoyrlCgZQPaOO0ZGyzVFLLFb2OuIJjzQFqlPLoQ


### 查询课程发布信息(内部微服务远程调用接口)
GET {{content_host}}/content/r/coursepublish/2
