### 上传文件
POST {{gateway_host}}/media//upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data;name="filedata"; filename="6.jpg"
Content-Type: application/octet-stream

< d:/java_lesson/upload/6.jpg


### 检查文件是否存在(通过md5)
POST {{gateway_host}}/media/upload/checkfile?fileMd5=0dbc6409995eaa9589676c585459e02b


### 检查文件是否存在(通过md5)
POST {{gateway_host}}/media/upload/checkchunk?fileMd5=0dbc6409995eaa9589676c585459e02b&chunk=23

### 上传分块
POST {{gateway_host}}/media/upload/uploadchunk?fileMd5=0dbc6409995eaa9589676c585459e02b&chunk=23


### 上传静态页面
POST {{gateway_host}}/media/upload/coursehtml?objectName=11.html
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data;name="filedata"; filename="11.html"
Content-Type: application/octet-stream

< d:/java_lesson/11.html