### 添加课程索引
POST {{search_host}}/search/index/course
Content-Type: application/json

{
  "id": 130,
  "companyId": 1232141425,
  "companyName": null,
  "name": "测试课程104",
  "users": "初级人员",
  "tags": "",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "teachmode": "200002",
  "description": "",
  "pic": "/mediafiles/2023/04/12/d527e6808f170f2257d8badf6e202cec.JPG",
  "createDate": "2023-03-06 16:02:03",
  "changeDate": null,
  "createPeople": null,
  "changePeople": null,
  "auditStatus": "202004",
  "status": "203002",
  "charge": "201000",
  "price": 256.0,
  "originalPrice": 2.0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mtName": "前端开发",
  "stName": "HTML/CSS"
}




### 搜索课程
GET {{search_host}}/search/course/list?pageNo=1&keywords=java
Content-Type: application/json